strassen:
	$ python strassen.py --size 64
	$ python strassen.py --size 256
	$ python strassen.py --size 1024

numpy:
	$ python numpy_matmul.py --size 64
	$ python numpy_matmul.py --size 256
	$ python numpy_matmul.py --size 1024

all: strassen numpy
